### ISSUE TITLE
Package can't be installed in Production.

### ISSUE THREAD

**Issue by RohanNF** [shunkosa/guest-article-vote-salesforce-community#26]
I get this error when I click on the Production/DE link (https://login.salesforce.com/packaging/installPackage.apexp?p0=04tf40000047wJPAAY) as given in the Readme:

"The package you attempted to install is a beta package, which you can only install in sandbox or Developer Edition organizations."

Could you please give the correct link for Prod and resolve this issue, @shunkosa?
Thanks in advance!

<img width="775" alt="Screenshot 2024-01-29 at 11 52 22 PM" src="https://github.com/shunkosa/guest-article-vote-salesforce-community/assets/145692800/32056399-a5b5-436b-908b-69f3c4633f3f">

**Comment by shunkosa** [comment]
@RohanNF Thank you for reporting and sorry for the inconvenience. I'll fix it soon!

**Comment by shunkosa** [comment]
Update the package version. See README.md and try again.
