### ISSUE TITLE
Tests issues

### ISSUE THREAD

**Issue by vincenzocunsolo** [shunkosa/guest-article-vote-salesforce-community#7]
Hi, thank you for this components. I have an issue when launch tests in my sandbox. I get this message **Access to entity 'Knowledge__kav' denied: Entity is not api accessible**. Any idea?

thanks :)

**Comment by shunkosa** [comment]
@vincenzocunsolo Just in case, is the installing user 'knowledge user'? And is lightning knowledge is enabled in your org?

**Comment by vincenzocunsolo** [comment]
Hi @shunkosa , yes lightning knowledge is enabled and the installing is 'knowledge user'. Thank you for your response

**Comment by shunkosa** [comment]
Thank you! Did you try to install this in Summer ‘20 preview org? or current Spring ‘20?

**Comment by vincenzocunsolo** [comment]
I check and probably is a Summer '20 preview but Salesforce wil upgrade sandboxes on May 29/30

**Comment by shunkosa** [comment]
Oh, sorry, I misunderstood the schedule! And I still cannot reproduce this issue. Did you try to install to only admin? or all users?
